# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
set_msg_config -id {Common-41} -limit 4294967295
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z045ffg900-2
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:zc706:part0:1.0 [current_project]
set_param project.compositeFile.enableAutoGeneration 0
set_property default_lib xil_defaultlib [current_project]
add_files e:/saberui/python/python/rom_init.coe
add_files -quiet E:/Xilinx_Vivado_SDK_Win_2014.2_0612_1/vivado_projects/toeplitz/toeplitz.runs/blk_memory_synth_1/blk_memory.dcp
set_property used_in_implementation false [get_files E:/Xilinx_Vivado_SDK_Win_2014.2_0612_1/vivado_projects/toeplitz/toeplitz.runs/blk_memory_synth_1/blk_memory.dcp]
read_verilog -library xil_defaultlib {
  E:/Xilinx_Vivado_SDK_Win_2014.2_0612_1/vivado_projects/toeplitz/toeplitz.srcs/sources_1/new/read_rom.v
  E:/Xilinx_Vivado_SDK_Win_2014.2_0612_1/vivado_projects/toeplitz/toeplitz.srcs/sources_1/new/test.v
}
read_xdc dont_buffer.xdc
set_property used_in_implementation false [get_files dont_buffer.xdc]
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir E:/Xilinx_Vivado_SDK_Win_2014.2_0612_1/vivado_projects/toeplitz/toeplitz.cache/wt [current_project]
set_property parent.project_dir E:/Xilinx_Vivado_SDK_Win_2014.2_0612_1/vivado_projects/toeplitz [current_project]
catch { write_hwdef -file test.hwdef }
synth_design -top test -part xc7z045ffg900-2
write_checkpoint test.dcp
report_utilization -file test_utilization_synth.rpt -pb test_utilization_synth.pb
