# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z045ffg900-2
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:zc706:part0:1.0 [current_project]
set_param project.compositeFile.enableAutoGeneration 0
set_property default_lib xil_defaultlib [current_project]

read_ip e:/Xilinx_Vivado_SDK_Win_2014.2_0612_1/vivado_projects/toeplitz/toeplitz.srcs/sources_1/ip/blk_memory/blk_memory.xci
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property is_locked true [get_files e:/Xilinx_Vivado_SDK_Win_2014.2_0612_1/vivado_projects/toeplitz/toeplitz.srcs/sources_1/ip/blk_memory/blk_memory.xci]

set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir E:/Xilinx_Vivado_SDK_Win_2014.2_0612_1/vivado_projects/toeplitz/toeplitz.cache/wt [current_project]
set_property parent.project_dir E:/Xilinx_Vivado_SDK_Win_2014.2_0612_1/vivado_projects/toeplitz [current_project]
catch { write_hwdef -file blk_memory.hwdef }
synth_design -top blk_memory -part xc7z045ffg900-2 -mode out_of_context

rename_ref -prefix_all blk_memory_
write_checkpoint -noxdef blk_memory.dcp
report_utilization -file blk_memory_utilization_synth.rpt -pb blk_memory_utilization_synth.pb
if { [catch {
  file copy -force E:/Xilinx_Vivado_SDK_Win_2014.2_0612_1/vivado_projects/toeplitz/toeplitz.runs/blk_memory_synth_1/blk_memory.dcp e:/Xilinx_Vivado_SDK_Win_2014.2_0612_1/vivado_projects/toeplitz/toeplitz.srcs/sources_1/ip/blk_memory/blk_memory.dcp
  write_verilog -force -mode synth_stub e:/Xilinx_Vivado_SDK_Win_2014.2_0612_1/vivado_projects/toeplitz/toeplitz.srcs/sources_1/ip/blk_memory/blk_memory_stub.v
  write_vhdl -force -mode synth_stub e:/Xilinx_Vivado_SDK_Win_2014.2_0612_1/vivado_projects/toeplitz/toeplitz.srcs/sources_1/ip/blk_memory/blk_memory_stub.vhdl
  write_verilog -force -mode funcsim e:/Xilinx_Vivado_SDK_Win_2014.2_0612_1/vivado_projects/toeplitz/toeplitz.srcs/sources_1/ip/blk_memory/blk_memory_funcsim.v
  write_vhdl -force -mode funcsim e:/Xilinx_Vivado_SDK_Win_2014.2_0612_1/vivado_projects/toeplitz/toeplitz.srcs/sources_1/ip/blk_memory/blk_memory_funcsim.vhdl
} _RESULT ] } { 
  send_msg_id runtcl-3 error "Unable to successfully create or copy supporting IP files."
  return -code error
}
